name: learn-env
channels:
  - conda-forge
  - defaults
dependencies:
    -  numpy
    - pandas
    - matplotlib
    - seaborn
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
    - scikit-learn
    - statsmodels
    - scipy
    - requests
    - beautifulsoup4
    - bokeh
